modLoader="javafml"
loaderVersion="[32,)" #forge version dep
issueTrackerURL="https://github.com/iChun/GooglyEyes/issues"

[[mods]]
    modId="googlyeyes"
    version="${file.jarVersion}" #mandatory
    displayName="GooglyEyes"
    displayURL="http://ichun.me/"
    authors="iChun"
    description='''
    Because why not?
    '''

[[dependencies.googlyeyes]]
    modId="ichunutil"
    mandatory=true
    versionRange="[9.0.0,10)"
    ordering="NONE"
    side="BOTH"
