modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/GooglyEyes/issues"

[[mods]]
    modId="googlyeyes"
    version="${file.jarVersion}" #mandatory
    displayName="Googly Eyes"
    displayURL="http://ichun.me/"
    authors="iChun"
    description='''
    Because why not?
    '''

[[dependencies.googlyeyes]]
    modId="ichunutil"
    mandatory=true
    versionRange="[10.2.0,11)"
    ordering="NONE"
    side="BOTH"
